/**
 * Bible Word Wise Vocabulary
 * level 1 = hardest (shown even on "fewest hints")
 * level 2 = intermediate (shown on middle setting)
 * level 3 = somewhat difficult (shown on "most hints")
 *
 * Format: { word: { def: "short definition", level: 1|2|3 } }
 */
export const BIBLE_VOCAB = {
  // ── Level 1: Theological / Archaic / Specialized ───────────────────────────
  propitiation:      { def: "appeasing God's wrath by sacrifice", level: 1 },
  expiation:         { def: "removal of guilt through sacrifice", level: 1 },
  imputation:        { def: "crediting sin or righteousness to another", level: 1 },
  predestination:    { def: "God's foreordaining of events", level: 1 },
  foreordained:      { def: "decided by God in advance", level: 1 },
  sanctification:    { def: "process of becoming holy", level: 1 },
  justification:     { def: "declared righteous before God", level: 1 },
  propitiatory:      { def: "making atonement for sin", level: 1 },
  circumcision:      { def: "cutting of foreskin as covenant sign", level: 1 },
  uncircumcised:     { def: "not circumcised; outside covenant", level: 1 },
  theophany:         { def: "visible manifestation of God", level: 1 },
  eschatology:       { def: "study of end times", level: 1 },
  soteriology:       { def: "doctrine of salvation", level: 1 },
  pneumatology:      { def: "doctrine of the Holy Spirit", level: 1 },
  dispensation:      { def: "era of God's dealing with humanity", level: 1 },
  kenosis:           { def: "Christ's self-emptying in incarnation", level: 1 },
  hypostatic:        { def: "relating to two natures of Christ", level: 1 },
  omniscience:       { def: "all-knowing attribute of God", level: 1 },
  omnipotence:       { def: "all-powerful attribute of God", level: 1 },
  omnipresence:      { def: "present everywhere simultaneously", level: 1 },
  shekinah:          { def: "God's glorious dwelling presence", level: 1 },
  tabernacle:        { def: "portable sanctuary for God in the wilderness", level: 1 },
  ephod:             { def: "priestly garment worn over robe", level: 1 },
  urim:              { def: "sacred lot used for divine guidance", level: 1 },
  thummim:           { def: "sacred lot used for divine guidance", level: 1 },
  phylacteries:      { def: "small boxes with scripture worn by Jews", level: 1 },
  sackcloth:         { def: "rough cloth worn in mourning or repentance", level: 1 },
  pentecost:         { def: "Jewish harvest festival; day of Holy Spirit", level: 1 },
  passover:          { def: "feast commemorating Israel's exodus from Egypt", level: 1 },
  synagogue:         { def: "Jewish house of worship and assembly", level: 1 },
  sanhedrin:         { def: "Jewish supreme ruling council of 71 men", level: 1 },
  centurion:         { def: "Roman army officer commanding 100 soldiers", level: 1 },
  anathema:          { def: "formally cursed; set apart for destruction", level: 1 },
  drachma:           { def: "Greek silver coin", level: 1 },
  denarius:          { def: "Roman silver coin worth a day's wage", level: 1 },
  shekel:            { def: "Hebrew unit of weight and money", level: 1 },
  cubit:             { def: "ancient measure of about 18 inches", level: 1 },
  myrrh:             { def: "bitter aromatic resin used in burial and anointing", level: 1 },
  frankincense:      { def: "fragrant white resin burned as incense", level: 1 },
  spikenard:         { def: "expensive aromatic ointment from India", level: 1 },
  alabaster:         { def: "white translucent stone used for perfume jars", level: 1 },
  scepter:           { def: "ornamental staff symbolizing royal authority", level: 1 },
  threshing:         { def: "separating grain from stalks by beating", level: 1 },
  winnowing:         { def: "tossing grain to blow away chaff", level: 1 },
  oblation:          { def: "offering or sacrifice made to God", level: 1 },
  supplication:      { def: "earnest humble prayer or petition to God", level: 1 },
  intercession:      { def: "praying to God on behalf of others", level: 1 },
  consecration:      { def: "setting apart as sacred and holy", level: 1 },
  ordination:        { def: "authorizing and setting apart for ministry", level: 1 },
  libation:          { def: "liquid poured out as an offering to God", level: 1 },
  firstfruits:       { def: "first portion of harvest offered to God", level: 1 },
  tithe:             { def: "tenth part of income given to God", level: 1 },
  manna:             { def: "miraculous bread sent from heaven for Israel", level: 1 },
  praetorium:        { def: "Roman governor's official residence or court", level: 1 },
  golgotha:          { def: "\"Place of the Skull\"; site of Jesus' crucifixion", level: 1 },
  gethsemane:        { def: "olive garden where Jesus prayed before arrest", level: 1 },
  gehenna:           { def: "valley near Jerusalem; symbol of eternal punishment", level: 1 },
  sheol:             { def: "Hebrew concept of the realm of the dead", level: 1 },
  hades:             { def: "Greek concept of the realm of the dead", level: 1 },
  incarnation:       { def: "God taking on human flesh in Jesus Christ", level: 1 },
  atonement:         { def: "reconciliation between God and man through sacrifice", level: 1 },
  cherubim:          { def: "powerful heavenly beings guarding God's presence", level: 1 },
  seraphim:          { def: "fiery heavenly beings worshipping God's throne", level: 1 },
  leviathan:         { def: "great sea creature; symbol of chaos and evil", level: 1 },
  behemoth:          { def: "enormous land creature; symbol of God's power", level: 1 },
  hosanna:           { def: "Hebrew cry: \"Save now!\"; shout of praise", level: 1 },
  hallelujah:        { def: "Hebrew: \"Praise the LORD!\"; highest praise", level: 1 },
  amen:              { def: "\"so be it\"; affirming truth of a statement", level: 1 },
  selah:             { def: "musical pause or meditation marker in Psalms", level: 1 },
  maranatha:         { def: "Aramaic: \"Come, Lord!\" or \"Our Lord has come\"", level: 1 },
  tetrarch:          { def: "ruler over a quarter of a region", level: 1 },
  procurator:        { def: "Roman provincial administrator and judge", level: 1 },
  jubilee:           { def: "50th year of rest, release, and restoration", level: 1 },
  atonement:         { def: "making amends; God reconciling humanity to himself", level: 1 },
  imputed:           { def: "credited to one's account; attributed to another", level: 1 },
  exegesis:          { def: "careful critical explanation of scripture", level: 1 },
  hermeneutics:      { def: "principles for interpreting scripture", level: 1 },

  // ── Level 2: Important Biblical Terms ────────────────────────────────────
  covenant:          { def: "solemn binding agreement between God and people", level: 2 },
  righteousness:     { def: "being morally right and just before God", level: 2 },
  righteous:         { def: "morally right; in right standing with God", level: 2 },
  redemption:        { def: "being set free by payment of a ransom price", level: 2 },
  redeemer:          { def: "one who pays to buy freedom for another", level: 2 },
  salvation:         { def: "deliverance from sin, death, and judgment", level: 2 },
  sanctify:          { def: "to make holy; set apart for God's purposes", level: 2 },
  glorify:           { def: "to honor, praise, and reveal God's greatness", level: 2 },
  glorified:         { def: "transformed into divine glory; raised to honor", level: 2 },
  transgression:     { def: "deliberate violation of God's law; sin", level: 2 },
  iniquity:          { def: "gross wickedness; deeply corrupt behavior", level: 2 },
  repentance:        { def: "turning away from sin and toward God", level: 2 },
  repent:            { def: "to turn away from sin with regret", level: 2 },
  reconcile:         { def: "to restore a broken relationship to peace", level: 2 },
  reconciliation:    { def: "restored peace between estranged parties", level: 2 },
  anoint:            { def: "to pour oil on as sign of God's blessing and choice", level: 2 },
  anointed:          { def: "chosen and empowered by God for a special purpose", level: 2 },
  apostle:           { def: "\"sent one\"; messenger sent with authority by Jesus", level: 2 },
  prophet:           { def: "one who speaks God's message to the people", level: 2 },
  prophecy:          { def: "divinely inspired message spoken for God", level: 2 },
  prophesy:          { def: "to speak a message from God; to predict", level: 2 },
  parable:           { def: "short story using everyday scenes to teach spiritual truth", level: 2 },
  baptism:           { def: "ritual immersion in water symbolizing new life in Christ", level: 2 },
  resurrection:      { def: "rising bodily from death to new and eternal life", level: 2 },
  ascension:         { def: "Jesus' bodily rising into heaven after resurrection", level: 2 },
  tribulation:       { def: "intense period of suffering and trial", level: 2 },
  dominion:          { def: "power and authority to rule over something", level: 2 },
  sovereign:         { def: "having supreme power and authority", level: 2 },
  sovereignty:       { def: "God's absolute supreme power over all creation", level: 2 },
  mediator:          { def: "one who stands between two parties to bring peace", level: 2 },
  advocate:          { def: "one who pleads another's case before a judge", level: 2 },
  intercede:         { def: "to pray to God on behalf of someone else", level: 2 },
  consecrate:        { def: "to dedicate solemnly to God's service", level: 2 },
  exaltation:        { def: "being raised to the highest position of honor", level: 2 },
  exalt:             { def: "to raise to the highest honor and glory", level: 2 },
  wrath:             { def: "God's intense righteous anger against sin", level: 2 },
  desolation:        { def: "a state of complete ruin and emptiness", level: 2 },
  abomination:       { def: "something deeply disgusting and offensive to God", level: 2 },
  blasphemy:         { def: "speaking with contempt or irreverence about God", level: 2 },
  blaspheme:         { def: "to speak sacrilegiously about God or sacred things", level: 2 },
  idolatry:          { def: "worship of idols, images, or false gods", level: 2 },
  idol:              { def: "a false god; any object of misplaced worship", level: 2 },
  heathen:           { def: "people who do not know God; pagans", level: 2 },
  gentile:           { def: "a non-Jewish person; those outside Israel", level: 2 },
  pharisee:          { def: "strict Jewish religious leader; known for external rule-keeping", level: 2 },
  sadducee:          { def: "Jewish religious leader who rejected resurrection and angels", level: 2 },
  scribe:            { def: "Jewish expert who copied and interpreted religious law", level: 2 },
  levite:            { def: "member of the tribe of Levi; temple assistant", level: 2 },
  priest:            { def: "one who offers sacrifices to God on behalf of others", level: 2 },
  altar:             { def: "raised structure used for making offerings and sacrifices", level: 2 },
  gospel:            { def: "good news of salvation through Jesus Christ", level: 2 },
  testament:         { def: "covenant; the two main divisions of Scripture", level: 2 },
  scripture:         { def: "the inspired sacred writings; the Bible", level: 2 },
  messiah:           { def: "God's promised anointed deliverer; the Christ", level: 2 },
  baptize:           { def: "to immerse in water as a rite of faith", level: 2 },
  disciple:          { def: "a learner and committed follower of a teacher", level: 2 },
  steadfast:         { def: "firmly fixed and unwavering in faith and purpose", level: 2 },
  steadfastness:     { def: "firm and unwavering determination to continue", level: 2 },
  remnant:           { def: "a small faithful group remaining after judgment", level: 2 },
  sabbath:           { def: "seventh day of rest commanded by God", level: 2 },
  ark:               { def: "the large boat Noah built; or the sacred chest of God", level: 2 },
  exodus:            { def: "Israel's dramatic departure from slavery in Egypt", level: 2 },
  plague:            { def: "a catastrophic disaster sent as divine judgment", level: 2 },
  locust:            { def: "swarming insect that devours crops; sign of judgment", level: 2 },
  vineyard:          { def: "land planted with grapevines; used as symbol for Israel", level: 2 },
  covenant:          { def: "binding agreement with God sealed by sacrifice", level: 2 },
  transgress:        { def: "to break God's law; to go beyond set boundaries", level: 2 },
  unrighteous:       { def: "not right before God; sinful and unjust", level: 2 },
  profane:           { def: "treating the sacred as if it were common; ungodly", level: 2 },
  sanctified:        { def: "made holy; set apart and dedicated to God", level: 2 },
  redeemed:          { def: "bought back; set free from sin and bondage", level: 2 },
  justified:         { def: "declared righteous by God; acquitted of sin", level: 2 },
  ungodly:           { def: "without reverence for God; living contrary to God", level: 2 },
  perverse:          { def: "turned away from what is right; morally corrupt", level: 2 },
  zeal:              { def: "intense devotion and eagerness for God", level: 2 },
  zealous:           { def: "passionately devoted to God or a cause", level: 2 },
  consecrated:       { def: "formally set apart for God's holy purpose", level: 2 },
  abide:             { def: "to remain; to continue to live in fellowship", level: 2 },
  abides:            { def: "remains; continues to dwell and stay", level: 2 },
  abundance:         { def: "overflowing supply; richly more than enough", level: 2 },
  harvest:           { def: "gathering of crops; used for spiritual gathering of souls", level: 2 },
  generation:        { def: "all people born at the same time; an age of people", level: 2 },
  nations:           { def: "all peoples of the earth; Gentiles beyond Israel", level: 2 },
  trespass:          { def: "a sin or offense against God or another person", level: 2 },
  trespasses:        { def: "sins and offenses committed against God or others", level: 2 },
  harlot:            { def: "a prostitute; figuratively, spiritual unfaithfulness", level: 2 },
  genealogy:         { def: "recorded list of ancestors and family lineage", level: 2 },
  leprosy:           { def: "serious skin disease making one ceremonially unclean", level: 2 },

  // ── Level 3: Archaic / KJV English / Less Common Biblical Words ───────────
  grace:             { def: "undeserved kindness and favor from God", level: 3 },
  mercy:             { def: "compassion shown to those who deserve punishment", level: 3 },
  humble:            { def: "having a modest view of oneself before God", level: 3 },
  humility:          { def: "freedom from pride; submissive meekness before God", level: 3 },
  solemn:            { def: "formal, serious, and deeply sincere", level: 3 },
  sacred:            { def: "set apart as holy and dedicated to God", level: 3 },
  eternal:           { def: "without beginning or end; lasting forever", level: 3 },
  wicked:            { def: "morally evil and corrupt", level: 3 },
  wickedness:        { def: "evil behavior; moral depravity and corruption", level: 3 },
  blameless:         { def: "without moral fault; living with integrity", level: 3 },
  upright:           { def: "morally honest and just in one's conduct", level: 3 },
  dwelling:          { def: "a place of residence; where someone lives or stays", level: 3 },
  affliction:        { def: "pain, suffering, or hardship", level: 3 },
  afflicted:         { def: "suffering from pain, trouble, or distress", level: 3 },
  famine:            { def: "widespread severe shortage of food", level: 3 },
  pestilence:        { def: "a fatal epidemic disease spread widely", level: 3 },
  perish:            { def: "to die; to be eternally destroyed", level: 3 },
  forsake:           { def: "to abandon completely; to leave behind forever", level: 3 },
  forsaken:          { def: "completely abandoned; left utterly alone", level: 3 },
  lament:            { def: "an expression of deep grief and sorrow", level: 3 },
  mourn:             { def: "to feel and express deep grief or sorrow", level: 3 },
  mourning:          { def: "a period of grief over loss or sin", level: 3 },
  compassion:        { def: "deep sympathy with a strong desire to help", level: 3 },
  fervent:           { def: "intensely earnest; showing passionate commitment", level: 3 },
  fervently:         { def: "with great intensity, passion, and sincerity", level: 3 },
  diligence:         { def: "careful, persistent, and thorough effort", level: 3 },
  diligent:          { def: "hardworking and careful in one's actions", level: 3 },
  perseverance:      { def: "continuing steadfastly despite difficulty or delay", level: 3 },
  persevere:         { def: "to keep going faithfully despite hardship", level: 3 },
  everlasting:       { def: "lasting forever without end; eternal", level: 3 },
  desolate:          { def: "barren and empty; stripped of inhabitants", level: 3 },
  forsook:           { def: "abandoned; past tense of forsake", level: 3 },
  vanity:            { def: "emptiness; meaninglessness; futile pride", level: 3 },
  vain:              { def: "empty; worthless; producing no result", level: 3 },
  entrust:           { def: "to place something in the care of another", level: 3 },
  boast:             { def: "to brag proudly; to take improper pride", level: 3 },
  woe:               { def: "great sorrow, distress, or trouble; a warning cry", level: 3 },
  lest:              { def: "for fear that; in order to prevent", level: 3 },
  behold:            { def: "look! pay attention! (calling notice to something)", level: 3 },
  henceforth:        { def: "from this time forward; from now on", level: 3 },
  hitherto:          { def: "until now; up to this point in time", level: 3 },
  begotten:          { def: "brought into existence; fathered; uniquely born", level: 3 },
  slaughter:         { def: "killing of many; sacrificing of animals", level: 3 },
  smite:             { def: "to strike with a hard blow; to defeat", level: 3 },
  smote:             { def: "struck hard; defeated; past tense of smite", level: 3 },
  smitten:           { def: "struck; beaten; deeply affected", level: 3 },
  midst:             { def: "the middle; surrounded by others or something", level: 3 },
  chaff:             { def: "the worthless husks of grain blown away in wind", level: 3 },
  sow:               { def: "to plant seeds in the ground", level: 3 },
  reap:              { def: "to harvest crops; to receive results of one's actions", level: 3 },
  flock:             { def: "a group of sheep; used for a group of believers", level: 3 },
  shepherd:          { def: "one who tends and cares for sheep; God cares as shepherd", level: 3 },
  yoke:              { def: "a wooden bar joining two animals; a burden or obligation", level: 3 },
  garment:           { def: "an article of clothing; a robe or covering", level: 3 },
  cloak:             { def: "a loose outer garment worn as a covering", level: 3 },
  sandal:            { def: "a simple foot covering made of leather", level: 3 },
  loins:             { def: "the area around the hips; seat of strength", level: 3 },
  kindle:            { def: "to set on fire; to arouse strong emotion", level: 3 },
  kindled:           { def: "set ablaze; aroused to strong emotion like anger", level: 3 },
  brethren:          { def: "brothers; fellow believers (archaic plural)", level: 3 },
  concubine:         { def: "a secondary wife permitted in ancient culture", level: 3 },
  leper:             { def: "a person with leprosy; considered ceremonially unclean", level: 3 },
  withered:          { def: "dried up; lost vitality or strength", level: 3 },
  cistern:           { def: "an underground reservoir for storing rainwater", level: 3 },
  sepulchre:         { def: "a tomb; a burial chamber carved in rock", level: 3 },
  sorrow:            { def: "deep sadness; distress caused by loss or sin", level: 3 },
  thee:              { def: "old English for \"you\" (object form)", level: 3 },
  thou:              { def: "old English for \"you\" (subject form)", level: 3 },
  thy:               { def: "old English for \"your\"", level: 3 },
  thine:             { def: "old English for \"yours\"", level: 3 },
  ye:                { def: "old English for \"you\" (plural)", level: 3 },
  hath:              { def: "old English: \"has\"", level: 3 },
  hast:              { def: "old English: \"have\" (second person)", level: 3 },
  doth:              { def: "old English: \"does\"", level: 3 },
  art:               { def: "old English: \"are\" (second person)", level: 3 },
  wilt:              { def: "old English: \"will\" (second person)", level: 3 },
  wouldst:           { def: "old English: \"would\" (second person)", level: 3 },
  shouldst:          { def: "old English: \"should\" (second person)", level: 3 },
  shalt:             { def: "old English: \"shall\" (second person)", level: 3 },
  canst:             { def: "old English: \"can\" (second person)", level: 3 },
  knoweth:           { def: "old English: \"knows\"", level: 3 },
  saith:             { def: "old English: \"says\"", level: 3 },
  sayeth:            { def: "old English: \"says\"", level: 3 },
  goeth:             { def: "old English: \"goes\"", level: 3 },
  doeth:             { def: "old English: \"does\"", level: 3 },
  cometh:            { def: "old English: \"comes\"", level: 3 },
  maketh:            { def: "old English: \"makes\"", level: 3 },
  taketh:            { def: "old English: \"takes\"", level: 3 },
  giveth:            { def: "old English: \"gives\"", level: 3 },
  loveth:            { def: "old English: \"loves\"", level: 3 },
  dwelleth:          { def: "old English: \"dwells; lives\"", level: 3 },
  speaketh:          { def: "old English: \"speaks\"", level: 3 },
  walketh:           { def: "old English: \"walks\"", level: 3 },
  leadeth:           { def: "old English: \"leads\"", level: 3 },
  seeketh:           { def: "old English: \"seeks\"", level: 3 },
  believeth:         { def: "old English: \"believes\"", level: 3 },
  receiveth:         { def: "old English: \"receives\"", level: 3 },
  thereof:           { def: "of that; of it; concerning that thing", level: 3 },
  therein:           { def: "in that place; in that matter or document", level: 3 },
  thereupon:         { def: "immediately after that; as a result", level: 3 },
  thereof:           { def: "of that thing; belonging to it", level: 3 },
  wherefore:         { def: "for what reason; why; therefore", level: 3 },
  whereby:           { def: "by which means; by what method", level: 3 },
  wherein:           { def: "in which; in what place or way", level: 3 },
  wherewith:         { def: "with which; by means of which", level: 3 },
  hereafter:         { def: "in the future; the life after death", level: 3 },
  heretofore:        { def: "before now; in the past up to this moment", level: 3 },
  albeit:            { def: "although; even though", level: 3 },
  naught:            { def: "nothing; zero; of no value", level: 3 },
  nought:            { def: "nothing; zero (variant spelling)", level: 3 },
  yea:               { def: "yes; indeed; truly (old English)", level: 3 },
  nay:               { def: "no; not that; on the contrary", level: 3 },
  verily:            { def: "truly; certainly; in truth", level: 3 },
  surely:            { def: "certainly; without doubt; confidently", level: 3 },
  thus:              { def: "in this way; therefore; as a result", level: 3 },
  hence:             { def: "for this reason; from this place or time", level: 3 },
  hearken:           { def: "to listen carefully; pay attention to", level: 3 },
  hearken:           { def: "to hear and heed; to give attentive ear", level: 3 },
  beseech:           { def: "to beg earnestly; to plead urgently", level: 3 },
  besought:          { def: "past tense of beseech; begged urgently", level: 3 },
  implore:           { def: "to beg desperately and urgently", level: 3 },
  entreat:           { def: "to ask earnestly and humbly", level: 3 },
  entreat:           { def: "to plead; to ask with urgency and humility", level: 3 },
  prevail:           { def: "to overcome; to gain victory; to succeed", level: 3 },
  prevailed:         { def: "succeeded; gained the upper hand; won", level: 3 },
  rebuke:            { def: "to scold or correct sharply with authority", level: 3 },
  rebuked:           { def: "corrected or scolded with authority", level: 3 },
  rebuke:            { def: "sharp correction or reprimand given with authority", level: 3 },
  exhort:            { def: "to urge strongly; to encourage and challenge", level: 3 },
  exhortation:       { def: "urgent encouragement or strong appeal", level: 3 },
  edify:             { def: "to build up spiritually; to instruct and strengthen", level: 3 },
  edification:       { def: "spiritual building up and strengthening of faith", level: 3 },
  admonish:          { def: "to gently warn and counsel against wrong", level: 3 },
  admonition:        { def: "gentle warning and wise counsel", level: 3 },
  exhort:            { def: "to urge and encourage with strong words", level: 3 },
  contrite:          { def: "feeling deep sorrow and regret for sin", level: 3 },
  contrition:        { def: "genuine remorse and sorrow for sin", level: 3 },
  penitent:          { def: "feeling regret and turning from sin", level: 3 },
  sojourner:         { def: "a temporary resident; a stranger living among others", level: 3 },
  sojourn:           { def: "to live temporarily in a place; to dwell briefly", level: 3 },
  pilgrimage:        { def: "a journey to a sacred place; life as journey toward God", level: 3 },
  remnant:           { def: "a small remaining group after judgment", level: 3 },
  exiles:            { def: "people forced to live far from their homeland", level: 3 },
  captive:           { def: "one held as prisoner; taken away from homeland", level: 3 },
  captivity:         { def: "the state of being held as prisoner; exile", level: 3 },
  bondage:           { def: "slavery; being bound and controlled by another", level: 3 },
  deliverance:       { def: "being rescued and set free from danger or bondage", level: 3 },
  oppression:        { def: "cruel or unjust use of power against others", level: 3 },
  oppressed:         { def: "treated cruelly and unjustly by those in power", level: 3 },
  steadfast:         { def: "firmly committed and unwavering in loyalty", level: 3 },
  fervent:           { def: "intensely devoted; burning with zeal", level: 3 },
  bountiful:         { def: "giving generously and abundantly; very plentiful", level: 3 },
  gracious:          { def: "showing kindness, courtesy, and generosity", level: 3 },
  merciful:          { def: "showing compassion to those in need or at fault", level: 3 },
  faithful:          { def: "consistently loyal, reliable, and trustworthy", level: 3 },
  wrathful:          { def: "intensely angry; filled with righteous indignation", level: 3 },
  longsuffering:     { def: "patiently enduring trouble or offense for a long time", level: 3 },
  forbearance:       { def: "patient restraint; holding back judgment", level: 3 },
  temperance:        { def: "self-control; moderation in desires and behavior", level: 3 },
  sobriety:          { def: "seriousness; clearness of mind; not drunk", level: 3 },
  prudent:           { def: "wise in practical matters; careful and sensible", level: 3 },
  prudence:          { def: "wise and careful judgment in conduct", level: 3 },
  counsel:           { def: "wise advice; guidance given to help decide", level: 3 },
  discern:           { def: "to perceive clearly; to judge and distinguish", level: 3 },
  discernment:       { def: "the ability to judge wisely and spiritually", level: 3 },
  revelation:        { def: "God unveiling hidden truth; the last book of the Bible", level: 3 },
  vision:            { def: "a dream-like sight from God; spiritual seeing", level: 3 },
  anguish:           { def: "extreme mental or physical suffering", level: 3 },
  despair:           { def: "complete loss of hope", level: 3 },
  steadfast:         { def: "firmly loyal and constant; unshaken", level: 3 },
  trembling:         { def: "shaking from fear or reverence before God", level: 3 },
  prostrate:         { def: "lying face down in worship or submission", level: 3 },
  adoration:         { def: "deep worship and reverent love", level: 3 },
  vengeance:         { def: "punishment inflicted in return for a wrong", level: 3 },
  retribution:       { def: "deserved punishment for wrongdoing", level: 3 },
  recompense:        { def: "reward or punishment given as due return", level: 3 },
  recompense:        { def: "to make a return for good or ill done", level: 3 },
  wayward:           { def: "going one's own way; disobedient to God", level: 3 },
  stubborn:          { def: "refusing to change; stiff-necked and resistant", level: 3 },
  stiff:             { def: "rigid and unyielding; used of a stubborn will", level: 3 },
  groan:             { def: "to make a deep sound of pain or longing", level: 3 },
  groaning:          { def: "deep sounds of pain, longing, or spiritual longing", level: 3 },
  intercede:         { def: "to plead on behalf of another before God", level: 3 },
  suppliant:         { def: "one who humbly begs and pleads for help", level: 3 },
  multitude:         { def: "a very large number of people or things", level: 3 },
  uttermost:         { def: "to the farthest point; the very extreme", level: 3 },
  uttermost:         { def: "to the greatest degree possible", level: 3 },
  girded:            { def: "bound tightly; prepared; dressed for action", level: 3 },
  gird:              { def: "to bind or fasten; to prepare oneself for action", level: 3 },
  breastplate:       { def: "armor protecting the chest; used as spiritual metaphor", level: 3 },
  quench:            { def: "to extinguish; to put out fire or satisfy thirst", level: 3 },
  steadfast:         { def: "immovably firm in faith and devotion", level: 3 },
  perished:          { def: "died; was destroyed completely", level: 3 },
  appointed:         { def: "officially chosen and set apart for a purpose", level: 3 },
  ordained:          { def: "officially appointed and set apart by God", level: 3 },
  proclaimed:        { def: "announced publicly and officially", level: 3 },
  transgressed:      { def: "broke the law; went beyond the boundary set", level: 3 },
  toil:              { def: "exhausting hard work; to work very hard", level: 3 },
  tribulation:       { def: "great trouble and suffering; trial", level: 3 },
};

/**
 * Get vocabulary entries to show based on level setting
 * setting 1 = fewest hints (only level 1 words)
 * setting 2 = medium (level 1 + 2)
 * setting 3 = most hints (level 1 + 2 + 3)
 */
export function getActiveVocab(setting) {
  const result = {};
  for (const [word, entry] of Object.entries(BIBLE_VOCAB)) {
    if (entry.level <= setting && entry.def) {
      result[word] = entry;
    }
  }
  return result;
}

/**
 * Tokenize a verse text into words + punctuation/spaces
 * Returns array of { text, word } where word is the clean lowercase word (or null)
 */
export function tokenizeVerse(text) {
  const tokens = [];
  // Split preserving spaces and punctuation
  const parts = text.split(/(\s+)/);
  for (const part of parts) {
    if (!part) continue;
    if (/^\s+$/.test(part)) {
      tokens.push({ text: part, word: null });
    } else {
      // Strip leading/trailing punctuation to get clean word
      const clean = part.replace(/^[^a-zA-Z']+|[^a-zA-Z']+$/g, '').toLowerCase();
      tokens.push({ text: part, word: clean || null });
    }
  }
  return tokens;
}
